version: '3'

services:
  my-react-app-prod:
    build: ./notes-ui
    container_name: my-react-app-prod
    ports:
      - "3003:3000"
    volumes:
      - ./notes-ui:/app  
    links:
      - my-db-prod

  my-backend-prod:
    build: ./server 
    container_name: my-backend-prod
    environment:
      - APP_ENV=test  
    ports:
      - "4008:4006"
    volumes:
      - ./server:/app  
    links:
      - my-db-prod

  my-db-prod:
    build: ./server/database
    container_name: dev-db-prod
    ports:
      - "3308:3306"
    volumes:
      - server-database:/var/lib/mysql 

volumes:
       server-database:
