version: '3'

services:
  my-react-app:
    build: ./notes-ui
    container_name: my-react-app
    ports:
      - "3000:3000"
    volumes:
      - ./notes-ui:/app  # Mount the local notes-ui directory into the container
    links:
      - my-db

  my-backend:
    build: ./server 
    container_name: my-backend
    environment:
      - APP_ENV=test  
    ports:
      - "4006:4006"
    volumes:
      - ./server:/app  # Mount the local server directory into the container
    links:
      - my-db

  my-db:
    build: ./server/database
    container_name: dev-db
    ports:
      - "3306:3306"
    volumes:
      - ./server/database:/app 
