version: '3'

services:
  my-react-app-uat:
    build: ./notes-ui
    container_name: my-react-app-uat
    ports:
      - "3002:3000"
    volumes:
      - ./notes-ui:/app  
    links:
      - my-db

  my-backend-uat:
    build: ./server 
    container_name: my-backend-uat
    environment:
      - APP_ENV=test  
    ports:
      - "4007:4006"
    volumes:
      - ./server:/app  
    links:
      - my-db

  my-db-uat:
    build: ./server/database
    container_name: dev-db-uat
    ports:
      - "3307:3306"
    volumes:
      - server-database:/var/lib/mysql 

volumes:
       server-database:
