version: '3'

services:
  my-react-app:
    build: ./notes-ui
    container_name: my-react-app-prod
    ports:
      - "3002:3000"
    links:
      - my-db

  my-backend:
    build: ./server 
    container_name: my-backend-prod
    environment:
      - APP_ENV=test  
    ports:
      - "4002:4006"
    links:
      - my-db

  my-db:
    build: ./server/database
    container_name: dev-db-prod
    ports:
      - "3302:3306"
