version: '3.3'

services:
  my-backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4001:4006"
    volumes:
      - .:/app
    environment:
      - APP_ENV=test

  my-react-app-dev:
    build:
      context: ./notes-ui
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=test
