version: '3'

services:

  my-react-app:
    build: ./notes-ui
    container_name: my-react-app
    ports:
      - "3002:3000"

  my-backend:
    build: ./server 
    container_name: my-backend-uat
    ports:
      - "4002:4006"

  database:
    build: ./server/database
    container_name: my_database
    ports:
      - "3306:3306"




