version: '3'

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home

  my-react-app-uat:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPO}:my-react-app-uat
    container_name: my-react-app-uat
    ports:
      - "3002:3000"

  my-backend-uat:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPO}:my-backend-uat
    container_name: my-backend-uat
    ports:
      - "4002:4006"

volumes:
  jenkins_data:


