version: '3.3'

services:
  node_app_4006:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4001:4006"
    volumes:
      - .:/app
    environment:
      - APP_ENV=test

  node_app_3000:
    build:
      context: ./notes-ui
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=test
