version: '3'

services:
  my-react-app:
    build: ./notes-ui
    container_name: my-react-app
    ports:
      - "3000:3000"

  my-backend:
    build: ./server 
    container_name: my-backend
    environment:
      - APP_ENV=test  
    ports:
      - "4006:4006"


  my-db:
      build: ./server/database
      container_name: dev-db
      ports:
        - "3306:3306"





