version: '3'

services:
  my-react-app:
    build: ./notes-ui
    image: dev-frontend:v1
    ports:
      - "3000:3000"

  my-backend:
    build: ./server 
    image: dev-backend:v1
    environment:
      - APP_ENV=test  
    ports:
      - "4006:4006"


  my-db:
      build: ./server/database
      ports:
        - "3306:3306"





